markdown: kramdown
title: Shinonome Lab, funded by NERV
<html>
<body background="https://i0.hdslb.com/bfs/article/d0fb73d2b85ce5a39b8e97601b30e29fdb69f5af.jpg@1256w_754h_!web-article-pic.webp"
      style="background-repeat: no-repeat";
      background-attachment: fixed;
      background-size: contain>
</body>
</html>
